Fix initialization
blue-heron/blue_heron pull request #85
Opened 2022-03-15 22:33 UTC by amclain

This PR fixes a couple issues I ran into when trying to run the [`scanner.ex`](https://github.com/blue-heron/blue_heron/blob/main/examples/scanner.ex) example with a [Realtek rtl8761b](https://www.amazon.com/dp/B08CMP5LQC?psc=1&ref=ppx_yo2_dt_b_product_details) USB dongle (VID=`0x0BDA`, PID=`0x8771`). On initialization of the Bluetooth dongle the GenServer would timeout:

```text
iex(1)> {:ok, pid} = BlueHeronScan.start_link(:usb, %{pid: 0x8771})

15:27:30.955 [warning] BlueHeron(USB): Using BT device at bus 3, device 8: ID 0bda:8771
{:ok, #PID<0.284.0>}
iex(2)> 
15:27:35.952 [error] Timeout executing Init commands
 
15:27:40.953 [error] Timeout executing Init commands
 
15:27:45.955 [error] Timeout executing Init commands
** (EXIT from #PID<0.282.0>) shell process exited with reason: :reached_max_error
```

The first place seems to be from `{:next_event, :internal, :init}` not getting emitted after each `prepare()` completed (26eaf58). The second looks like it was from the `send_command()` call not receiving a reply (ea4a51c).

2022-03-21 22:31 UTC, amclain commented
Thanks for the info and for passing this on!

FWIW I had originally tried this with a [Kinovo dongle](https://www.amazon.com/gp/product/B007Q45EF4) that uses the Broadcom BCM20702A0 chipset (vid `0x0A5C`, pid `0x21E8`) but experienced the same issue so I got a Realtek dongle since it's officially supported.

2022-09-29 15:20 UTC, ConnorRigby commented on lib/blue_heron/hci/transport.ex
> +        {:keep_state, add_call(data, {from, opcode}), {:reply, from, :ok}}
Can you remove this change? it breaks the contract of the `send_command` function.

2022-09-29 15:20 UTC, ConnorRigby requested changes
Sorry it took so long on this @amclain , but i've tested it and found an issue with that reply added in the second commit.

2022-09-29 18:43 UTC, amclain commented on lib/blue_heron/hci/transport.ex
> +        {:keep_state, add_call(data, {from, opcode}), {:reply, from, :ok}}
I'll have to refresh my memory on this, but I recall having to make this change because the prior code caused a hang or crash and this was a blocker. I'm sure Blue Heron has evolved since I opened this PR, so I'll take a look at this again with a fresh set of eyes.

2022-12-15 18:37 UTC, jasonmj commented on lib/blue_heron/hci/transport.ex
> +        {:keep_state, add_call(data, {from, opcode}), {:reply, from, :ok}}
@amclain I tested `scanner.ex` from this repo and the [gatt server example](https://github.com/livebook-dev/nerves_livebook/blob/main/priv/samples/bluetooth/ble_device_with_nerves.livemd) from `nerves_livebook` using your change on line 190 while **excluding** this change on line 214. It resolves the issues with initialization timeout. 

However, including this `:ok` reply from line 214, produces issues with modules that expect a tagged tuple response like `{:ok, %CommandComplete{}}`. In particular, `peripheral.ex` produces this error when attempting to set advertising parameters for the gatt server example:

![](https://i.imgur.com/Y6u83ZW.png)

I think removing the change on line 214 from this PR would get the desired results and maintain the contract of the `send_command` function.

2025-01-02 18:03 UTC, ConnorRigby commented
Recent updates to BlueHeron make this not needed anymore. Feel free to rebase/reopen if necessary.

2025-01-02 18:03 UTC, closed without merging